proxy=""                 # socks5://127.0.0.1:1080
freq=1                   # unit: second, 60 for 1min
[user]
username="admin"      #  username for login
password="AbcdEfgh"   # password for login and encrypts and decrypts your apiseckey to store in database
